layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: cooper-goodman
  # mastodon: your_username
  medium: cooper-goodman
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: GoodmanPlanFan
  # unsplash: your_username
  # vk: your_username
  website: https://cgplanning.me/
  # youtube: your_username

topics:
  - name: Jupyter Notebook
    web_url: https://github.com/topics/jupyter-notebook
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jupyter-notebook/jupyter-notebook.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: R
    web_url: https://github.com/topics/r
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/r/r.png

  # - name:
  #   web_url:
  #   image_url:

  # - name:
  #   web_url:
  #   image_url:

  # - name:
  #   web_url:
  #   image_url:

  # - name:
  #   web_url:
  #   image_url: